name: BlockHunt
main: ru.mclegendary.blockhunt.BlockHunt
authors: [pepej, mclegendary]
version: '4.3'
website: https://squareland.ru
softdepend: [FeatherBoard, HideAndSeek, iConomy]
description:
  blockhunnt.* - Все права этого плагина
  blockhunt.chat - Возможность видеть чат других миров/Посылать туда сообщения
  blockhunt.adm - админ права на команды
  blockhunt.kick.* - Все права на кик
  blockhunt.kick.other - Возможность исключать игроков с арены
  blockhunt.kick.bypass - Обход кика(НЕ РАБОТАЕТ НА МИРЫ)
  blockhunt.togglechat - Возможность выключения чата на миры

permissions:
    blockhunt.*:
      default: false
      children:
        blockhunt.chat:
          default: op
        blockhunt.adm:
          default: op
        blockhunt.kick.*:
          default: false
          children:
            blockhunt.kick.other:
              default: op
            blockhunt.kick.bypass:
              default: false
        blockhunt.togglechat:
          default: op

commands:
  lottery:
    description: 'Gives random cash number(from: to:) to player'
    usage: From console only = /<command> <player> <from number> <to number>
    permission: blockhunt.adm
  exchange:
    description: 'Exchange'
    usage: From console only = /<command> <money/coins> <player> <one> <to another>
    permission: blockhunt.adm
  csgo:
    description: 'CSGO crate exchanger'
    usage: From console only! = /<command> give <player> <crate-name> <amount> <price>
    permission: blockhunt.adm
  where:
    description: 'Checking where is player'
    usage: /<command> <online player>
    permission: blockhunt.adm
  bh:
    usage: |
     §с/<command> §b<kick> <Игрок> [Причина]
     §с/<command> §b<kickall> <Мир> [Причина]
    permission: blockhunt.kick.other
  op:
    usage: /<command> <player>
  deop:
    usage: /<command> <player>
  chat:
    usage: |
      §b/<command> on §e-> §b Включить чат на миры
      §b/<command> off §e-> §b Выключить чат на миры
      §b/<command> toggle §e-> §b Переключить чат на миры
      §b/<command> info §e-> §b Узнать состояние чата
    permission: blockhunt.togglechat





