name: BlockHunt
main: ru.mclegendary.blockhunt.BlockHunt
authors: [pepej, mclegendary]
version: '4.6'
website: https://squareland.ru
softdepend: [FeatherBoard, HideAndSeek, iConomy]
description:
  blockhunnt.* - Все права этого плагина
  blockhunt.chat - Возможность видеть чат других миров/Посылать туда сообщения
  blockhunt.adm - админ права на команды
  blockhunt.kick.* - Все права на кик
  blockhunt.kick.other - Возможность исключать игроков с арены
  blockhunt.kick.bypass - Обход кика(НЕ РАБОТАЕТ НА МИРЫ)
  blockhunt.reloadconfig - перезагрузка конфига

permissions:
    blockhunt.*:
      default: false
      children:
        blockhunt.chat:
          default: op
        blockhunt.adm:
          default: op
        blockhunt.kick.*:
          default: false
          children:
            blockhunt.kick.other:
              default: op
            blockhunt.kick.bypass:
              default: false
        blockhunt.reloadconfig:
          default: op
        blockhunt.togglechat:
          default: op



commands:
  lottery:
    description: 'Gives random cash number(from: to:) to player'
    usage: '§c/<command> <игрок> <от> <до>'
  exchange:
    description: 'Exchange'
    usage: '§c/<command> <money/coins> <игрок> <забрать> <дать>'
  csgo:
    description: 'CSGO crate exchanger'
    usage: '§c/<command> give <игрок> <название кейса> <кол-во> <цена>'
  where:
    description: 'Узнать в каком мире находится игрок'
    usage: /<command> <Игрок>
    permission: blockhunt.adm
  bh:
    usage: '§c/bh help§b чтобы увидеть список доступных команд'

    permission: blockhunt.kick.other
  op:
    usage: '§c/<command> <player>'
  deop:
    usage: '§c/<command> <player>'







