name: BlockHunt
main: ru.mclegendary.blockhunt.BlockHunt
authors: [pepej, mclegendary]
version: 'RELEASE'
website: https://squareland.ru
softdepend: [FeatherBoard, HideAndSeek, iConomy]

permissions:
    blockhunt.*:
      default: false
      children:
        blockhunt.chat:
          default: op
        blockhunt.adm:
          default: op
        blockhunt.kick.*:
          default: false
          children:
            blockhunt.kick.other:
              default: op
            blockhunt.kick.bypass:
              default: false
        blockhunt.reloadconfig:
          default: op




commands:
  lottery:
    description: 'Gives random cash number(from: to:) to player'
    usage: '§c/<command> <игрок> <от> <до>'
  exchange:
    description: 'Exchange'
    usage: '§c/<command> <money/coins> <игрок> <забрать> <дать>'
  csgo:
    description: 'CSGO crate exchanger'
    usage: '§c/<command> give <игрок> <название кейса> <кол-во> <цена>'
  where:
    description: 'Узнать в каком мире находится игрок'
    usage: "/§c<command> <Игрок>"
  bh:
    usage: '§c/bh help§b чтобы увидеть список доступных команд'
  op:
    usage: '§c/<command> <Игрок>'
  deop:
    usage: '§c/<command> <Игрок>'







